package graph

// This file will be partially auto-generated by gqlgen

type Resolver struct {
	// TODO: Add database connection
}

// TODO: Implement resolver methods
// - Register
// - Login
// - Me
