package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"log"

	"github.com/greenbuildr/auth-service/domain/services"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string) (bool, error) {
	err := r.RegisterService.Register(ctx, services.RegisterInput{Email: email, Password: password})
	if err != nil {
		log.Printf("register error: %v", err)
		return false, toGQLError(err)
	}
	return true, nil
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, token string) (bool, error) {
	err := r.RegisterService.VerifyEmail(ctx, token)
	if err != nil {
		return false, toGQLError(err)
	}
	return true, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (string, error) {
	token, err := r.LoginService.Login(ctx, services.LoginInput{Email: email, Password: password})
	if err != nil {
		log.Printf("login error: %v", err)
		return "", toGQLError(err)
	}
	return token, nil
}

// RequestPasswordReset is the resolver for the requestPasswordReset field.
func (r *mutationResolver) RequestPasswordReset(ctx context.Context, email string) (bool, error) {
	if err := r.ResetPasswordService.RequestPasswordReset(ctx, email); err != nil {
		return false, toGQLError(err)
	}
	return true, nil
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, token string, newPassword string) (bool, error) {
	if err := r.ResetPasswordService.ResetPassword(ctx, token, newPassword); err != nil {
		return false, toGQLError(err)
	}
	return true, nil
}

// ResendVerificationEmail is the resolver for the resendVerificationEmail field.
func (r *mutationResolver) ResendVerificationEmail(ctx context.Context, email string) (bool, error) {
	if err := r.RegisterService.ResendVerificationEmail(ctx, email); err != nil {
		return false, toGQLError(err)
	}
	return true, nil
}

// Empty is the resolver for the _empty field.
func (r *queryResolver) Empty(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Empty - _empty"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
